### ISSUE TITLE
Config option to disable storing history

### ISSUE THREAD

**Issue by CompeyDev** [Magic-JD/is-fast#18]
Title is self-explanatory. Here is what I propose:

```toml
[history]
enabled = false # Defaults to `true`
```
